services:
  web:
    image: webdevops/php-apache-dev:8.2-alpine
    container_name: api-laravel-back
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    user: "root"
    depends_on: 
      - dbsneakers
    networks:
      - app-network

  dbsneakers:
    image: mysql:8.3
    container_name: sneakers-mysql
    volumes:
      - db:/var/lib/mysql/
    ports:
      - '${FORWARD_DB_PORT:-3307}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    networks:
      - app-network

volumes:
  db:
    driver: local

networks:
  app-network:
    driver: bridge